// The research site is generated by Jekyll. Sites serves the static build.
export default {
  async fetch(request, env) {
    const response = await env.ASSETS.fetch(request);
    if (!response.headers.get('content-type')?.includes('text/html')) return response;
    const url = new URL(request.url);
    const pageUrl = url.origin + url.pathname;
    const imageUrl = new URL('/images/og.png', url.origin).href;
    return new HTMLRewriter()
      .on('link[rel="canonical"]', { element(el) { el.setAttribute('href', pageUrl); } })
      .on('meta[property="og:url"]', { element(el) { el.setAttribute('content', pageUrl); } })
      .on('meta[property="og:image"], meta[name="twitter:image"]', { element(el) { el.setAttribute('content', imageUrl); } })
      .transform(response);
  }
};
